# Allow EFUSE access, used by OP-TEE
YAML_COMPILER_FLAGS:append:zynqmp = " -DENABLE_EFUSE_ACCESS"

# Options set via meta-kria at the BSP release
YAML_COMPILER_FLAGS:append:k26 = " -DBOARD_SHUTDOWN_PIN=2 -DBOARD_SHUTDOWN_PIN_STATE=0 -DENABLE_EM -DENABLE_MOD_OVERTEMP -DOVERTEMP_DEGC=90.0 -DENABLE_DYNAMIC_MIO_CONFIG -DENABLE_IOCTL -DCONNECT_PMU_GPO_2_VAL=0"
# Disabled as with ENABLE_EFUSE_ACCESS there is not enough PMU_RAM
YAML_COMPILER_FLAGS:remove:k26 = "-DENABLE_DYNAMIC_MIO_CONFIG"
